// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function toNumber(n) {
  return Curry._2(n, (function (i) {
                return i + 1 | 0;
              }), 0);
}

function zero(f, x) {
  return x;
}

function one(f, x) {
  return Curry._1(f, x);
}

function two(f, x) {
  return Curry._1(f, Curry._1(f, x));
}

function three(f, x) {
  return Curry._1(f, Curry._1(f, Curry._1(f, x)));
}

toNumber(three);

function add(n, m, f, x) {
  return Curry._2(m, f, Curry._2(n, f, x));
}

function four(param, param$1) {
  return add(one, three, param, param$1);
}

toNumber(four);

exports.toNumber = toNumber;
exports.zero = zero;
exports.one = one;
exports.two = two;
exports.three = three;
exports.add = add;
exports.four = four;
/*  Not a pure module */
