// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");

function unfold(p, g, b) {
  if (Curry._1(p, b)) {
    return /* [] */0;
  } else {
    var match = Curry._1(g, b);
    return /* :: */[
            match[0],
            unfold(p, g, match[1])
          ];
  }
}

function example(param) {
  return unfold((function (x) {
                return x > 9;
              }), (function (x) {
                return /* tuple */[
                        x,
                        x + 1 | 0
                      ];
              }), param);
}

example(7);

exports.unfold = unfold;
exports.example = example;
/*  Not a pure module */
